matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8.3
      env:
        - SWIFT_VERSION=3.0
      before_install:
        export UUID=$(instruments -s | ruby -e "ARGF.each_line{ |ln| ln =~ /$NAME .* \[(.*)\]/; if \$1; puts(\$1); exit; end }");
      before_script:
        - echo "SWIFT_VERSION=$SWIFT_VERSION" > Base.xcconfig 
        - cat Base.xcconfig
      script:
        - ! (Pods/SwiftLint/swiftlint --reporter emoji 2> /dev/null | tee /dev/fd/2 | grep "⛔️" > /dev/null)
        - set -o pipefail && xcodebuild build test -workspace BeaconKit.xcworkspace -scheme BeaconKitTests -sdk iphonesimulator -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= | xcpretty
    - os: osx
      language: objective-c
      osx_image: xcode9
      env:
        - SWIFT_VERSION=3.0
      before_script:
        - echo "SWIFT_VERSION=$SWIFT_VERSION" > Base.xcconfig 
        - cat Base.xcconfig
      script:
        - ! (Pods/SwiftLint/swiftlint --reporter emoji 2> /dev/null | tee /dev/fd/2 | grep "⛔️" > /dev/null)
        - set -o pipefail && xcodebuild build test -workspace BeaconKit.xcworkspace -scheme BeaconKitTests -sdk iphonesimulator -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= | xcpretty
    - os: osx
      language: objective-c
      osx_image: xcode9
      env:
        - SWIFT_VERSION=4.0
      before_script:
        - echo "SWIFT_VERSION=$SWIFT_VERSION" > Base.xcconfig 
        - cat Base.xcconfig
      script:
        - ! (Pods/SwiftLint/swiftlint --reporter emoji 2> /dev/null | tee /dev/fd/2 | grep "⛔️" > /dev/null)
        - set -o pipefail && xcodebuild build test -workspace BeaconKit.xcworkspace -scheme BeaconKitTests -sdk iphonesimulator -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= | xcpretty
